config/routes.rb
RailsContributors::Application.routes.draw do
  get 'contributors/in-time-window/:time_window' => 'contributors#in_time_window', as: 'contributors_in_time_window'

  resources :contributors, only: 'index' do
    get 'commits/in-time-window/:time_window' => 'commits#in_time_window', as: 'commits_in_time_window'
    get 'commits/in-release/:release_id'      => 'commits#in_release',     as: 'commits_in_release'
    get 'commits/in-edge'                     => 'commits#in_edge',        as: 'commits_in_edge'

    resources :commits, only: 'index'
  end

  resources :releases, only: 'index' do
    resources :commits,      only: 'index'
    resources :contributors, only: 'index'
  end

  get 'edge/contributors' => 'contributors#in_edge', as: 'contributors_in_edge'

  resource :faq, only: :show

  root to: 'contributors#index'
end

app/views/shared/_window_sidebar.html.erb
<% content_for :sidebar do %>
  <ul id="navigation">
    <% in_faq         = controller_name == 'faqs' %>
    <% in_release     = @release || @releases %>
    <% in_edge        = @edge %>
    <% in_time_window = !in_release && !in_edge && !in_faq %>

    <% for key, name in TimeConstraints.all %>
      <% path = key == 'all-time' ? contributors_path : contributors_in_time_window_path(key) %>
      <%# TODO: clean this %>
      <%= sidebar_tab name, in_time_window && ((@time_window.nil? && key == 'all-time') || @time_window == key), path %>
    <% end %>
    <%= sidebar_tab 'Releases', in_release, releases_path %>
    <%= sidebar_tab 'Edge', in_edge, contributors_in_edge_path %>
    <%= sidebar_tab 'FAQ', in_faq, faq_path %>
  </ul>
<% end %>