config/routes.rb
RailsContributors::Application.routes.draw do
  get 'contributors/in-time-window/:time_window' => 'contributors#in_time_window', as: 'contributors_in_time_window'

  resources :contributors, only: 'index' do
    get 'commits/in-time-window/:time_window' => 'commits#in_time_window', as: 'commits_in_time_window'
    get 'commits/in-release/:release_id'      => 'commits#in_release',     as: 'commits_in_release'
    get 'commits/in-edge'                     => 'commits#in_edge',        as: 'commits_in_edge'

    resources :commits, only: 'index'
  end

  resources :releases, only: 'index' do
    resources :commits,      only: 'index'
    resources :contributors, only: 'index'
  end

  get 'edge/contributors' => 'contributors#in_edge', as: 'contributors_in_edge'

  resource :faq, only: :show

  root to: 'contributors#index'
end

app/controllers/releases_controller.rb
class ReleasesController < ApplicationController
  caches_page :index

  def index
    @releases = Release.all_with_ncommits_and_ncontributors
  end
end

app/views/releases/_release.html.erb
<tr class="<%= cycle 'even', 'odd' %> release">
  <td class="release-tag"><%= link_to_release_in_github release %></td>
  <td class="release-date"><%= date release.date %></td>
  <td class="release-name"><%= link_to_release release %></td>
  <td class="release-counter"><%= link_to release.ncontributors, release_contributors_path(release) %></td>
  <td class="release-counter"><%= link_to release.ncommits, release_commits_path(release) %></td>
</tr>

app/views/releases/index.html.erb
<%
   @title       = 'GitLab Releases'
   @description = 'Listing of GitLab releases'
   @keywords    = 'releases'
%>

<!-- see http://google.com/support/webmasters/bin/answer.py?hl=en&answer=99170 -->
<div class="vcard">
  <h1 id="title">
    <%= @title %><br/>
    <span class="listing-total">Showing <%= pluralize @releases.size, 'releases' %></span>
  </h1>

  <div id="table-wrap">
    <table id="releases">
      <tr class="header">
        <th>Tag</th>
        <th>Date</th>
        <th>Release</th>
        <th>Contributors</th>
        <th>Commits</th>
      </tr>
      <%= render @releases %>
    </table>
  </div>
</div>

<%= render 'shared/window_sidebar' %>